Update dependency
bendrucker/replace-requires pull request #5
Opened 2017-04-23 16:25 UTC by furstenheim

This PR fixes #4

2017-04-23 20:37 UTC, bendrucker requested changes

2017-04-23 20:37 UTC, bendrucker commented on package.json
> +    "detective": "4.x.x",
Thanks! Please just change the `~` to a `^`, I prefer not to use `x` in package versions.

2017-04-23 20:37 UTC, bendrucker commented on test.js
> +  t.equal(replace('require("foo"); async function someFunction () {}', {foo: 'bar'}), 'bar; async function someFunction () {}')
Really appreciate the addition of a test!

2017-04-24 17:39 UTC, furstenheim commented on package.json
> +    "detective": "4.x.x",
Done. In the end I added ~ as well to make sure that npm uses the latest version in case there are other packages with the same dependency

2017-04-24 18:06 UTC, closed without merging